### ISSUE TITLE
extensions page

### ISSUE THREAD

**Issue by stpeter** [xsf/xmpp.org#91] opened 2015-11-10 21:20 UTC
How does https://github.com/xsf/xmpp.org/blob/master/content/pages/extensions.html work? It has a list of XEPs hardcoded in there, but it seems preferable for this to be dynamically generated...

**Comment by imaginator** [comment] 2015-11-11 18:20
I now have the extensions autobuilding. For example: http://new.xmpp.org/extensions/xep-0050.html

We'll need to add the right css files. @adambrault -what's going to be the best way to do this?

For the autogeneration of the extensions list... I'm happy to manually update that in the mean time. 

I'm now working on the generation of the PDFs.

**Comment by winfried** [comment] 2015-11-13 15:14
All tasks needed to generate html, pdf and index lists are already in the xsf-tools (as are some functions to automate some editorial tasks). Think we better should start thinking on how to integrate them into the workflow.

**Comment by imaginator** [comment] 2015-11-13 15:40
@winfried did you see https://github.com/xsf/xmpp.org/blob/master/.travis.yml and https://github.com/xsf/xmpp.org/blob/master/Makefile#L107 ?

**Comment by winfried** [comment] 2015-11-13 15:56
I didn't look at the travis file, but I saw line 107 of the makefile.

What are you trying to ask or tell me?

**Comment by imaginator** [comment] 2015-11-13 16:40
Sorry for not being clearer. So the generate the XEPs I am guessing we need something like: 

```
# wget two files until https://github.com/xsf/xeps/pull/122 can be merged
mkdir /tmp/xep-images
curl -o /tmp/xep-images/xmpp-text.pdf  http://xmpp.org/images/xmpp-text.pdf
curl -o /tmp/xep-images/xmpp.pdf       http://xmpp.org/images/xmpp.pdf
git clone https://github.com/xsf/xeps /tmp/xeps
git clone https://github.com/xsf/xsf-tools /tmp/xsf-tools 
/tmp/xsf-tools/build.py -x /tmp/xeps -o /home/travis/build/xsf/xmpp.org/output/extensions --imagepath /tmp/xep-images 
```
but end up with
```
Building XEP: ... /tmp/xeps/xep-0001.xml                    [1/367]Traceback (most recent call last):
  File "/tmp/xsf-tools/build.py", line 56, in <module>
    xeps.buildAll(showprogress=config.debug)
  File "/tmp/xsf-tools/xeputils/repository.py", line 214, in buildAll
    xep.buildXHTML(self.outpath, self.xslpath, self.imagespath)
TypeError: buildXHTML() takes at most 3 arguments (4 given)
```

Any idea what is missing or why this is failing?

**Comment by winfried** [comment] 2015-11-13 16:44
Yeah, bug in repository.py, will fix it later tonight. BTW: imagepath should point to the directory where xmpp-text and xmpp.pdf are.

**Comment by imaginator** [comment] 2015-11-13 16:56
Excellent. Thanks @winfried.

Yes -  /tmp/xep-images has the two files.

I'll watch for your fix and swap in a new Makefile for the website that looks more like https://github.com/xsf/xmpp.org/issues/91#issuecomment-156482804

**Comment by winfried** [comment] 2015-11-13 19:39
Fixed by xsf/xsf-tools@4d42f67

Note that build.py takes (at my box at least) appr. 20 minutes to build everything.
build.py also creates:
- xeplist.txt, a snippet of html that can be used for an overview table, like http://xmpp.org/xmpp-protocols/xmpp-extensions/
- xeps.xml, an overview of all xeps in xml
- xepbundle.tar.bz2, everything wrapped up

Also note the commandline argument is --imagespath, not --imagepath

**Comment by imaginator** [comment] 2015-11-16 09:55
@winfried it looked good up until build.py looks for texml's python module (https://travis-ci.org/xsf/xmpp.org#L773) 

Yet I see it being installed as part of the build process https://travis-ci.org/xsf/xmpp.org#L298 The module is installed into /usr/local/lib/... 

Can you give me some pointers as to how you have it setup on your test environment?

**Comment by winfried** [comment] 2015-11-16 10:10
In my test environmet the python Texml modules are in
/usr/local/lib/python2.7/dist-packages/, just like in your travis-ci
environment.

Can you check if /usr/local/lib/python2.7/dist-packages/ is in your
pythonpath?

**Comment by imaginator** [comment] 2015-11-16 10:26
Added now and it seems to be running....

https://travis-ci.org/xsf/xmpp.org

This is looking much better now. Thanks.

On 16 November 2015 at 11:10, Winfried Tilanus <notifications@github.com>
wrote:

> In my test environmet the python Texml modules are in
> /usr/local/lib/python2.7/dist-packages/, just like in your travis-ci
> environment.
>
> Can you check if /usr/local/lib/python2.7/dist-packages/ is in your
> pythonpath?
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xsf/xmpp.org/issues/91#issuecomment-156977760>.
>



-- 
Simon Tennant | CEO Buddycloud <http://buddycloud.com> | +49 17 8545 0880 |
Meet <https://calendly.com/simon-tennant/buddycloud-call>

**Comment by imaginator** [comment] 2015-11-16 10:37
@winfried: any chance we could have some incremental progress to stdout?

https://travis-ci.org/xsf/xmpp.org#L792 shows
```
/tmp/xsf-tools/build.py -x /tmp/xeps -o /home/travis/build/xsf/xmpp.org/output/extensions --imagespath /tmp/xep-images
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```
Perhaps just which XEP it's currently building. Would also be nice for "normal" use.

**Comment by imaginator** [comment] 2015-11-16 10:48
Just noticed the `-d` option. Testing that now.

**Comment by imaginator** [comment] 2015-11-16 11:23
https://travis-ci.org/xsf/xmpp.org/builds/91354956 shows the build of the html succeeding and indeed on PDF seems to succeed http://new.xmpp.org/extensions/xep-0050.pdf 

Is there a good way to find out where the PDF generation is failing?

**Comment by winfried** [comment] 2015-11-16 11:35
On 11/16/2015 12:23 PM, Simon Tennant wrote:
> Is there a good way to find out where the PDF generation is failing?

build.py will print out a report on parsing and build errors at the end
of the process.

Check also XEP-0324 XEP-0347: they are good examples of XEPs containing
images of different kinds, if they build ok, most XEPs will.

**Comment by imaginator** [comment] 2015-11-16 11:44
I see the report at https://travis-ci.org/xsf/xmpp.org/builds/91354956#L796. It's telling me that the build fails, but not why. 

Do these command lines options look sensible to you: https://travis-ci.org/xsf/xmpp.org/builds/91354956#L792 ?

**Comment by winfried** [comment] 2015-11-16 12:28
> I see the report at
> https://travis-ci.org/xsf/xmpp.org/builds/91354956#L796. It's telling me
> that the build fails, but not why.

Does the building of the xhtml succeed?

For each XEP build (both xhtml and pdf), the script creates a temporary
directory prefixed with XEPBuilder_. The last step when building a XEP
is copying the html or pdf to the out directory and cleaning up the
temporary directory.

When this last step fails, the cause can be that there is no pdf to
copy, meaning the step before it failed silently (what it shouldn't do)
or the copying itself failed. If the building of the xhtml also fails
then it is probably an issue with the copying it self (sufficient
rights?) otherwise there is probably some issue with xelatex.

I can try to create a more verbose mode that logs all sub-process output
and not only stderr.

> Do these command lines options look sensible to you:
> https://travis-ci.org/xsf/xmpp.org/builds/91354956#L792 ?

Yes, they do.

**Comment by imaginator** [comment] 2015-11-16 12:38
Actually, this is now working well (published to the gh_pages branch) https://github.com/xsf/xmpp.org/tree/gh-pages/extensions (but the logs suggest otherwise?!?)

One small issue: The XEPs refer to the following files that are XEP specific and shouldn't be in the root directory of the website.

Could you add a way to point to a relative directory instead of the root directory:

For example: http://new.xmpp.org/extensions/xep-0074.html  is pointing to
`/xmpp.css` and `/prettify.css`.

That's the last issue then I think we have the website + generation ready to launch.

**Comment by winfried** [comment] 2015-11-16 13:09
> One small issue: The XEPs refer to the following files that are XEP
> specific and shouldn't be in the root directory of the website.
> 
> Could you add a way to point to a relative directory instead of the root
> directory:
> 
> For example: http://new.xmpp.org/extensions/xep-0074.html is pointing to
> |/xmpp.css| and |/prettify.css|.

These are defined in xep.xsl that is in the xeps repo. The offending
links are:
../xmpp.css
../prettify.css
../prettify.js
But changing these right now, may break building the old site. So, if
you can't make a temporary fix, we need some coordinated action.

**Comment by bear** [comment] 2016-04-04 17:18
Extensions page is now generated by the xep tools

**Closed by bear** 2016-04-04 17:18 UTC
