### ISSUE TITLE
All incoming xmpp.org links used by xml2rfc.ietf.org are broken or outdated

### ISSUE THREAD

**Issue by Flowdalic** [xsf/xmpp.org#279] opened 2017-03-23 10:06 UTC
https://xml2rfc.tools.ietf.org/ links to the following broken links

- http://www.xmpp.org/extensions/refs/xsf-xeps.zip
- http://www.xmpp.org/extensions/refs/xsf-xeps.tgz
- http://www.xmpp.org/extensions/refs/

and the http://www.xmpp.org/extensions/rss.xml appears to be outdated.

**Comment by stpeter** [comment] 2017-03-23 13:31
Duplicate of https://github.com/xsf/xmpp.org/issues/224 ?

**Comment by Flowdalic** [comment] 2017-03-23 13:45
Ahh right, besides that the xsf-xeps.(zip|tgz) are broken again. You may want to note that in #224 and close this issue, or simply close #224. I leave that up to you.

**Comment by horazont** [comment] 2017-03-24 08:31
``make refs`` in the xeps repository at least provides a refs directory with all XEPs in it. It doesn’t build the zip and tgz files though.

I wonder how those were generated in the first place?

**Comment by intosi** [comment] 2017-03-24 09:17
Closing, dupe of #224 .

**Closed by intosi** 2017-03-24 09:17 UTC
