### ISSUE TITLE
disappearing navbar on latest stable pelican release

### ISSUE THREAD

**Issue by anjandev** [xsf/xmpp.org#698] opened 2020-04-10 23:05 UTC
As stated in https://github.com/xsf/xmpp.org/pull/697:

> Navbar is missing if you use a version of Pelican that's newer than what is mentioned in the readme

**Comment by guusdk** [comment] 2020-04-12 17:34
Thanks for your feedback. You're right. The issue is already being tracked. I am closing this as a duplicate of #506.

**Closed by guusdk** 2020-04-12 17:34 UTC
