### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by bear** [xsf/xmpp.org#184] opened 2016-05-23 18:47 UTC
The list of broken links can be found within this file:  http://bear.im/xmpp.org.404.txt

Going to close Issue #107 to allow us to focus on this new list.

**Comment by guusdk** [comment] 2016-05-24 07:41
Thanks for this! It's a great source of information! However, after working with it for a bit, I found a couple of things that could use some additional love:

1. Some of the URLs that are reported as 404 do exist and are accessible. I can think of two reasons why these would end up in your log: stuff was already fixed and we're looking at old log entries, and the log combines results from multiple virtual hosts
2. Some of the missing 404's seem to be artifacts from our own old code, and are 'rightfully missing'.

To remove already-fixed 404's, I'd suggest to:
- Parse only the last days access logs for 404's (either by grepping for the timestamp, or by rotating the access logs)
- Add your parsing script to a daily cronjob

Additionally, I'd like to identify the source of the 404's. When those are pages under our control, we're better of fixing those pages, than putting effort in restoring the stuff that they're linking to. To identify the stuff that we can fix 'at the source', we should:
- Parse the referrer from the access log (and check if those are under our control).

**Comment by SamWhited** [comment] 2016-08-20 20:11
Related: xsf/xeps#227 (`/xmpp-protocols/xmpp-extensions/submitting-a-xep/`)

**Comment by SamWhited** [comment] 2016-10-29 21:51
XEP-0001 links to `http://xmpp.org/protocols/ ` which appears to be dead.

**Comment by guusdk** [comment] 2017-06-14 19:51
@SamWhited The source of does no longer appear to have any of the links that you mention. Am I looking in the right place? If so, then I'd like to close this issue (and create new ones for future dead links)

**Comment by SamWhited** [comment] 2017-06-15 14:42
@guusdk I think I probably fixed the template to point to the new links, but since they were at one time in the XEPs, we should probably still make sure they work (since old copies of the HTML-ified XEPs might be cached all over the place).

**Comment by guusdk** [comment] 2017-06-15 15:00
Fair enough. So, these redirects are needed?

- `/protocols/` -> `/extensions/`
- `/xmpp-protocols/xmpp-extensions/submitting-a-xep/` -> `/about/standards-process.html#submitting-a-xep`

Where should `/extensions/tmp/` redirect to?

**Comment by SamWhited** [comment] 2017-06-15 15:04
Those seem right; I have no idea what `/extensions/tmp` was though. Maybe that was a really, really old version of the inbox? Just guessing.

**Comment by guusdk** [comment] 2017-06-15 15:06
https://web.archive.org/web/20140724050423/https://xmpp.org/extensions/tmp/

**Comment by penguineer** [comment] 2017-08-02 08:20
The link to the QXmpp library listed on https://xmpp.org/software/libraries.html is broken:

Should be http://www.qxmpp.org
but is https://xmpp.org/software/www.qxmpp.org

**Comment by guusdk** [comment] 2017-08-16 11:56
With all of the recent changes, `/protocols/` now works as intended.

I've just committed a new redirect for `/xmpp-protocols/xmpp-extensions/submitting-a-xep/` -> `/about/standards-process.html#submitting-a-xep`

The QXmmp library is no longer listed at all.

With these, most of the failing URLs described in this issue should be fixed. Lets create new GitHub issues for any remaining problems.

**Closed by guusdk** 2017-08-16 11:56 UTC
Labels: bug
